### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by durka** [pschanely/wildflower-touch#1]
This looks fun to play with! How can I do that? It sort of looks like a Cordova project, but apparently it isn't. Plus `index.html` looks for a `cordova.js` which doesn't exist.

**Comment by pschanely** [comment]
Indeed, it needs instructions; I've added some to the readme just now.  Would you be willing to test them and make sure I got it right?

Most functionality is broken or missing, so sadly, you may not get very far.  Honestly, I was just hoping to gather some preliminary feedback on whether this is an interesting approach.  Regardless, if you get it running, you should be able to start with:

```
(menu) => "new" => (title module)
(menu) => "new function" => (title function)
and be able to play with the operations a bit.
```

Let me know how it goes & I'll resolve this issue.  Thanks for the feedback & interest!

**Comment by pschanely** [comment]
Oh, and just to answer you more directly: it is, in fact a cordova project.  (and the `cordova.js` file is one that only exists when running it under cordova)  Though you should also be able to run it under a web server too  (you need a real web server for the cross-site script to load code from my repository ... though you can run your own repository too, see https://github.com/pschanely/wf-repository).  The cordova.js file won't be found but everything should still work ... or at least, in the chome debugger where you can emulate touch events.

**Comment by durka** [comment]
Yep, it builds! It doesn't exactly look like the demo GIF [on my device](https://dl.pushbulletusercontent.com/XvYsMXdGJOvppIbaIs7n0XegLJlSkDcz/Screenshot_2015-09-23-01-53-48.png), and I can't click on anything, but what did I expect? :p

**Comment by pschanely** [comment]
Yeah, certainly not working, based on your screenshot: what is your device?  I know that [html dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) isn't supported on many devices (including ALL iOS devices), so I might just be able to add a polyfill for a quick fix - I'll take a look tonight.  Regardless, you should be able to try it out on a recent version of the android emulator.

**Comment by durka** [comment]
That's a Galaxy S4 with Android 4.4. It looks much the same on emulated Android 4.4, but on emulated Android 5.1 it seems to work. Regardless, I don't want to turn your side project into a remote debugging session!

**Comment by pschanely** [comment]
Nope, you've done just enough!  I've committed the dialog polyfill and now I believe (emulated) android 4.4 & ios work.  Thanks for your help!  Now, to get on to all the bugs in the actual application logic ... :)
